<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryAffiliate', 'doctrine');

/**
 * BaseCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property Category $Category
 * @property Affiliate $Affiliate
 * 
 * @method integer           getId()           Returns the current record's "id" value
 * @method integer           getCategoryId()   Returns the current record's "category_id" value
 * @method integer           getAffiliateId()  Returns the current record's "affiliate_id" value
 * @method Category          getCategory()     Returns the current record's "Category" value
 * @method Affiliate         getAffiliate()    Returns the current record's "Affiliate" value
 * @method CategoryAffiliate setId()           Sets the current record's "id" value
 * @method CategoryAffiliate setCategoryId()   Sets the current record's "category_id" value
 * @method CategoryAffiliate setAffiliateId()  Sets the current record's "affiliate_id" value
 * @method CategoryAffiliate setCategory()     Sets the current record's "Category" value
 * @method CategoryAffiliate setAffiliate()    Sets the current record's "Affiliate" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_affiliate');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('affiliate_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Affiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id'));
    }
}