<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Category', 'doctrine');

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property Doctrine_Collection $CategoryAffiliate
 * @property Doctrine_Collection $Job
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getSlug()              Returns the current record's "slug" value
 * @method Doctrine_Collection getCategoryAffiliate() Returns the current record's "CategoryAffiliate" collection
 * @method Doctrine_Collection getJob()               Returns the current record's "Job" collection
 * @method Category            setId()                Sets the current record's "id" value
 * @method Category            setName()              Sets the current record's "name" value
 * @method Category            setSlug()              Sets the current record's "slug" value
 * @method Category            setCategoryAffiliate() Sets the current record's "CategoryAffiliate" collection
 * @method Category            setJob()               Sets the current record's "Job" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('Job', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}