generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Job
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          job
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ =id, category, type, company, url, position ]
        max_per_page: 5
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
