all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=marco_jobeet'
      username: root
      password: root
      #username: wininjob
      #password: w6D74Ap6dY